# Traefik v1 Configuration
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[api]
  dashboard = true
  entryPoint = "traefik"
  [api.statistics]
    recentErrors = 10

[entryPoints]
  [entryPoints.traefik]
    address = ":8080"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "localhost"
  watch = true
  exposedByDefault = false
  network = "watch-together-network"

[acme]
  email = "admin@example.com"
  storage = "/etc/traefik/acme.json"
  entryPoint = "https"
  onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"

